#! /usr/local/bin/perl
use Cwd;
use lib cwd;
use strict;
use warnings;
use 5.010;

my @total = `perl sort.pl`;
$total[-1]=~ s/(\n|\r)*//g;
$total[-1]=~ s/.*?((\d|\.)+)$/$1/g;
my $working_total = $total[-1];
my $today_in_seconds = `date -d today +%s`;
$today_in_seconds=~ s/(\n|\r)*//g;
my $end_of_year_in_seconds = `date -d "31 Dec" +%s`;
$end_of_year_in_seconds=~ s/(\n|\r)*//g;
my $days_left = int(($end_of_year_in_seconds - $today_in_seconds)/ 86400);
say "There are $days_left days left";
my $target = (1100 - $working_total) / $days_left;
say "Target is $target";



