#! /usr/local/bin/perl
use Cwd;
use lib cwd;
use strict;
use warnings;
use 5.010;

my $days = shift || exit 0;

## run aggregate
my @lines = `./aggregate.pl | sort | tail -n $days`;
my $cutoffDate = `date -d "$days days ago" +%Y%m%d`;
my $count = 0;
foreach my $line (@lines)
{
	
	$line =~ /^(\d+)\s+(\d+\.?\d*)$/;
	my $date = $1;
	my $miles = $2;
	if ($date < $cutoffDate)
	{
		exit 0;
	}
	if ($miles < 1)
	{
		exit 0;
	}
	$count++
}
if($count == $days)
{
	say "On the wagon for $days days badge";
}


