#! /usr/local/bin/perl
use Cwd;
use lib cwd;
use strict;
use warnings;
use 5.010;

## run aggregate
my %totals;
my @lines = `./aggregate.pl | sort`;
my $day="20180101";
my $week=0;
my $total=0;
my $count=0;
my $thisWeek = `date +%V`;
$thisWeek=~ s/\D+//g;
$thisWeek++;


foreach my $line(@lines)
{
	$line =~ /^(\d+)\s+(\d+\.?\d*)$/;
        $totals{$1}=$2;
}

while($week < 52)
{
	$day=`date -d \"$day + 1 day\" +%Y%m%d`;
	$day =~ s/\D+//g;
	$week = `date -d \"$day\" +%V`;
	$week=~ s/\D+//g;
	##print $count." ";
	if($totals{$day})
	{
		$total+=$totals{$day};
	}
	$count++;
	if ($count == 7)
	{
		$count = 0;
		my $thisWeekTag="";
		if ($week == $thisWeek){$thisWeekTag=" THISWEEK"};
		say $total." ".$week." ".$day.$thisWeekTag;
	
		$total = 0;
	}
}
