#! /usr/local/bin/perl
use Cwd;
use lib cwd;
use strict;
use warnings;
use 5.010;

## run aggregate
my %totals;
my @lines = `./aggregate.pl | sort`;
my $day="20180101";
my $week=0;
my $total=0;
my $count=0;
my $thisWeek = `date +%V`;
my @weeks;
$thisWeek=~ s/\D+//g;
$thisWeek++;

foreach my $line(@lines)
{
	$line =~ /^(\d+)\s+(\d+\.?\d*)$/;
        $totals{$1}=$2;
}

while($week <= $thisWeek)
{
	$day=`date -d \"$day + 1 day\" +%Y%m%d`;
	$day =~ s/\D+//g;
	$week = `date -d \"$day\" +%V`;
	$week=~ s/\D+//g;
	##print $count." ";
	if($totals{$day})
	{
		$total+=$totals{$day};
	}
	$count++;
	if ($count == 7)
	{
		$count = 0;
		my $thisWeekTag="";
		if ($week == $thisWeek){$thisWeekTag=" THISWEEK"};
		##say $total." ".$week." ".$day.$thisWeekTag;
                push @weeks, $total." ".$week." ".$day.$thisWeekTag;	
		$total = 0;
	}
}
## sort by the total at the beginning of the line, in reverse order
my @rankedWeeks = sort {
  $a =~ /^(\d+(\.\d*)?|\.\d+)/;
  my $aa = $1;
  $b =~ /^(\d+(\.\d*)?|\.\d+)/;
  my $bb = $1;
  $bb <=> $aa;
} @weeks;

my $rankCount = 0;
my $currentTotal = 0;
my $previousTotal = 0;
foreach( @rankedWeeks )
{
	##say;
	$rankCount++;
	/^(\d+(\.\d*)?|\.\d+)/;
	$currentTotal = $1;
	if(/THISWEEK/)
        {
		say "Week Rank is $rankCount ($currentTotal Miles) Next Rank ($previousTotal Miles)";
		exit 0;
	}
	$previousTotal =$currentTotal;
}
